### ISSUE TITLE
ENS160+AHT2X no data to retrieve regarding Air Quality (NOT RELATED TO ESPHOME)

### ISSUE THREAD

**Issue by ale-ben** [ale-ben/Olive-Turtle-IoT#4]
ENS160+AHT2X connected I2C.
AHT2X works perfectly, ENS160 most of the times does not provide data.

_SparkFun Indoor Air Quality Sensor - ENS160_ library has a _checkDataStatus()_ function that checks the flag in the sensor for new data availability and the function **most of the times** return false.

_DFRobot_ENS160_ library does not have __checkDataStatus()_ and most of the times returns 0 on all values.

Suspect a defective sensor, waiting for seller to reply to understand if wiring is correct.

**Comment by ale-ben** [comment]
Replacing custom component code with https://github.com/esphome/esphome/pull/4243 does not resolve the problem, therefore this is not an implementation problem

**Comment by ale-ben** [comment]
Possible sensor replacements:
- [SGP30](https://esphome.io/components/sensor/sgp30)
- [CCS811](https://esphome.io/components/sensor/ccs811)
- [SM300D2](https://esphome.io/components/sensor/sm300d2) $$$$
- [SparkFun Environmental Combo Breakout - ENS160/BME280 (Qwiic)](https://www.sparkfun.com/products/22858)

**Comment by ghsensdev** [comment]
Does it mean you do not suggest buying this sensor?
Have someone tried the Adafruit breakboard with this sensor?

**Comment by ale-ben** [comment]
Not what I mean, in fact I am considering replacing this sensor with a sparkfun ENS160+BME combo shield.

It's just that this specific sensor (AHT2X+ENS160) is giving me problems, I tried contacting the seller to understand if I made some mistake but as of now "DFRobot_ENS160" lib most of the times returns 0 on all values and "SparkFun Indoor Air Quality Sensor - ENS160" lib returns "no data to retrieve".

Keep in mind this is an academic project so there is a non zero probability that I'm making a mistake somewhere...

Will update issue to be more specific, sorry for the misunderstanding

**Comment by ghsensdev** [comment]
When you are talking about "returns 0 on all values", which values do you want to get?
Does your bug block the merge into esphome?

**Comment by ale-ben** [comment]
Referring to all data provided by ENS160 (AQI, TVOC, eCO2, status).

It actually has nothing to do with esphome, I referenced the PR here as a way to keep track of my steps (since I was trying the implementation used there) but I forgot that GitHub keeps track of everywhere a PR has been mentioned...

As soon as I realized that my mention was appearing in the PR I removed the mention from here (but unfortunately it is still there)

**Comment by ale-ben** [comment]
__This is in no way a problem related to the ESPHome implementation of ENS160__, which, by the way, works perfectly (in my case returns the same error as the SparkFun lib but in less time)

**Comment by ghsensdev** [comment]
Have you tried the software on the official home  page of the sensor: https://downloads.sciosense.com/ens160/

**Comment by ale-ben** [comment]
I'm looking into it but as far as I understand I would need an I2C to USB converter and I have none

**Comment by ale-ben** [comment]
unless i make one using esp32

**Comment by ghsensdev** [comment]
If you use the sensor in ENS160_OPMODE_CUSTOM mode then only raw resistance values will be reported as I read somewhere. Do you use it in ENS160_OPMODE_STD mode?

**Comment by ale-ben** [comment]
Sorry for the late reply...
Can't find that mode in SparkFun_ENS160 lib.
Only modes I have are 
```// Possible Operating Mode defines:
#define SFE_ENS160_DEEP_SLEEP 0x00
#define SFE_ENS160_IDLE 0x01
#define SFE_ENS160_STANDARD 0x02
#define SFE_ENS160_RESET 0xF0```
